### ISSUE TITLE
Forward CI env vars in Docker containers

### ISSUE THREAD

**Issue by pyrech** [jolicode/docker-starter#125]
Now that some of our tools (like [PHPStan](https://github.com/phpstan/phpstan-src/blob/d77bd87da9f2fad0440fc1614158cdfc1b7cc88a/src/Command/ErrorFormatter/GithubErrorFormatter.php) & [Symfony linters](https://github.com/symfony/symfony/issues/39122)) adapt their output when they run on CI, we could make it working inside our Docker infrastructure.

For this to work we probably only need to forward all CI env vars to the builder container - in which our tools are executed.

**Comment by lyrixx** [comment]
@pyrech Would you mind to submit a PR?
