### ISSUE TITLE
Symfony app on root

### ISSUE THREAD

**Issue by supertanuki** [jolicode/docker-starter#14]
Hi!
Can we have the symfony app on the root of the project instead of in a subdirectory `app`? If yes, what we should set in `env.project_directory` ?
Thanks

**Comment by lyrixx** [comment]
Hello @supertanuki 

You can do that :+1: 

Did you encounter some issue by changing this value?

**Comment by pyrech** [comment]
Yep, setting `env.project_directory` to `../` is totally supported :wink:

**Comment by supertanuki** [comment]
I tried with '.' for env.project_directory but I have an error:

> ERROR: Service 'frontend' failed to build: pull access denied for myproject_basephp, repository does not exist or may require 'docker login': denied: requested access to the resource is denied
> Fatal error: local() encountered an error (return code 1) while executing 'docker-compose -p myproject -f /home/richard/Projects/myproject/myproject-website/infrastructure/docker/docker-compose.builder.yml -f /home/richard/Projects/myproject/myproject-website/infrastructure/docker/docker-compose.yml build --build-arg PROJECT_NAME=myproject --build-arg USER_ID=1000'

I tried it after being logged with my docker account, same error.

**Comment by lyrixx** [comment]
Actually, there is a random error with docker composer. 
Could you try another `fab start` ? It should be ok on the second run.
Is it OK now ?

**Comment by supertanuki** [comment]
I ran it 3 times, same error ^^

**Comment by lyrixx** [comment]
It's really weird. could you share with us a reproducer?

**Comment by Cydonia7** [comment]
I'm experiencing the same issue but I have no idea how I would share the reproducer here since I am using the base unmodified repository.

I'm thinking my Docker version might be the culprit:

```
Client:
 Version:           19.03.1-ce

Server:
 Engine:
  Version:          19.03.1-ce

docker-compose version 1.23.2, build 1110ad0
```

**Comment by lyrixx** [comment]
Hi all. 

As I did not get this issue on my computer, I were not so motivated to solve this issue.
I finally took time to tacle it and  #17 should fix your issue.

Thanks for the report and happy containering
