### ISSUE TITLE
Outdated webpack config

### ISSUE THREAD

**Issue by odolbeau** [jolicode/docker-starter#157]
It looks like the documentation contained in your README to use  `docker-starter` with webpack is outdated (using options which do not exist anymore).

I created an issue instead of a PR to directly correct the documentation because I have absolutely no idea of how to fix that... :sweat_smile:

**Comment by lyrixx** [comment]
Hola.

I tried to solve this issue but I was not able to 

The issue: **webpack should bind 0.0.0.0 and expose a custom host**

I'm able to;
* use a custom host and bind 127.0.0.1
* **OR** bind 0.0.0.0 and expose host `0.0.0.0`

If someone have the solution, it would be super nice !
