### ISSUE TITLE
Better DX with SSL certificates with mkcert

### ISSUE THREAD

**Issue by pyrech** [jolicode/docker-starter#165]
Currently, SSL is available by default with auto-signed certificates. We already propose an alternative in [a cookbook about Mkcert](https://github.com/jolicode/docker-starter#how-to-generate-locally-trusted-ssl-certificates-with-mkcert).

I suggest that we no longer provide self-signed SSL certificates BUT a start of the infrastructure should run by default a modified version of the task `generate_certificates`.

- if certifcates are already generated, do nothing;
- else it should generate certificates with mkcert if the tool is available;
- else it should generate auto-signed certificates with the script in [infrastructure/docker/services/router/generate-ssl.sh](https://github.com/jolicode/docker-starter/blob/main/infrastructure/docker/services/router/generate-ssl.sh) (it could ask a confirmation before generating certificates but I prefer that it works out of the box without having to do anything).

**Comment by lyrixx** [comment]
I like it a lot !
