### ISSUE TITLE
Add a Dockerfile linter?

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/docker-starter#196]
We could add a linter for Dockerfile in the CI.

https://github.com/hadolint/hadolint/blob/master/docs/INTEGRATION.md#github-actions

**Comment by lyrixx** [comment]
Good idea. Do you want to work on a PR?

**Comment by damienalexandre** [comment]
no. :kissing_heart:

**Comment by lyrixx** [comment]
Do you know a good linter?

**Comment by lyrixx** [comment]
https://twitter.com/dunglas/status/1660942656912891904 

https://github.com/hadolint/hadolint
