### ISSUE TITLE
probleme 502 bad gateway by nginx

### ISSUE THREAD

**Issue by kelplant** [jolicode/docker-starter#202]
Hello Jolicode, Hello @damienalexandre,

J'utilise toujous avec grand plaisir votre stack.

Je suis tombé sur un petit soucis de cache ces derniers temps avec des pages tjs en 502 bad gateway

En ajoutant dans le nginx.conf, ça semble résoudre le problème
            fastcgi_buffer_size 128k;
            fastcgi_buffers 4 256k;
            fastcgi_busy_buffers_size 256k;

Je ne sais pas si vous voulez integrer la modif !

Bonne journée à vous

Xavier

**Comment by lyrixx** [comment]
Hello, thanks for the feedback.

We don't have any issue with the current setup. So I'm going to close this issue.

But let's hope it can help other people if they have the same issue.

**Comment by kelplant** [comment]
Hello
Php 8.1.13 / Symfony 6.2 / api platform latest / easyadmin latest
Few mods added to php configuration (amqp / http / raphf)
Few containers added to the project but no way that could interfer (rundeck / vault / rabbitmq / permanent copy of builder for rundeck execution / portainer / permanent copy of builder for messenger async queue with 3 replicas)

The project is not evil load but easyadmin wan't even able to load dashboard without this modification

Had already the problem without easyadmin, just debugging api platform and all errors were hide by 502.
Wasn't able to use dd or dump, only var_dump wasn't landing on 502 but i really investigate the problem when easyadmin were not working

**Comment by damienalexandre** [comment]
Thanks for sharing the details :+1: 

We will keep that in mind - looks like it's relevant in some case of performance tuning too!

As of today, we are probably going to stick to Nginx default values for as long as we can as they work for us (on dozen of projects).

**Comment by kelplant** [comment]
yes ! 
Same here, i already used the stack 1/2 dozen of projects and never add a case like that.
Since i past some time to find how to solve the issue, i prefer report the information

@damienalexandre i perhaps got some fun subjects on Elasticsearch for you if you can be interested ;)

**Comment by lyrixx** [comment]
Closing as explained in [the previous comment](https://github.com/jolicode/docker-starter/issues/202#issuecomment-1375756692)

Thanks for the report
