### ISSUE TITLE
Add `fab ps` command

### ISSUE THREAD

**Issue by lyrixx** [jolicode/docker-starter#25]
`docker ps` is nice to get an overview of what is running. But it gets more complicated when one wants to see what is down.

I have see several projects with `fab ps` command and it think it's a good idea.

I think I would be faster to add it by myself but with this issue: 

1. I can get feedback: :+1:  or :-1: 
2. Someone could contribute it for the hacktoberfest :tada:

**Comment by welcoMattic** [comment]
As `fab ps` only list container for current project, I vote :+1: . Moreover, we can apply a filter on `docker ps` to show only useful columns.
