### ISSUE TITLE
The new Asset Mapper `importmap:install` command is missing

### ISSUE THREAD

**Issue by HedicGuibert** [jolicode/docker-starter#269]
Since [Symfony Asset Mapper](https://symfony.com/doc/current/frontend/asset_mapper.html) v6.4, a new command was introduced : `importmap:install`, which populates the new assets/vendor directory.

Running `castor start` on a project using Asset Mapper 6.4 will result in some 500 errors because this directory will be empty, since this new command is never ran.

However, adding it is quite painful because we must check that the current project is actually using Asset Mapper *and* at least in v6.4.

So, maybe we shouldn't do anything and let the concerned projects add a `docker_compose_run('bin/console importmap:install');` to their `install()` function themselves ?

But then, we should probably at least update the README to notify users about it ?

**Comment by lyrixx** [comment]
We can check if the importmap.php is here and then run the command? Like we already do with packages.json.

Would you mind submitting a PR?

**Comment by lyrixx** [comment]
Why? If the file exists, then the components is here, Isn't?

**Comment by HedicGuibert** [comment]
The importmap file exists in versions prior to the 6.4 version so no, checking it is not enough.
We should maybe check the .lock file then ? But ehhhh... This is not appealing

**Comment by lyrixx** [comment]
hmm, I think we can go very simple. This starter is for **new** project. It does not make sens to start a new project with a SF 6.3. So let's add a simple check on the presence of the file. It's not perfect, but it does the job. 

Then if someone use this **template** with a SF 6.3, they could simply remove 3LOC.

KISS!

**Comment by HedicGuibert** [comment]
Sir yes sir 🫡
