### ISSUE TITLE
Unable to contact frontend service from builder

### ISSUE THREAD

**Issue by kissifrot** [jolicode/docker-starter#30]
Hello,

In our environment we need to be able to keep `network_mode: "host"` for `router` service while being able to connect to `frontend` one from  `builder` service, for functional testing purpose with Panther ( ❤️ ).
However using this mode Panther doesn't know how to reach the application on frontend (specified using `PROJECT_DOMAINS`).

Do you have any idea on how to do it?

**Comment by kissifrot** [comment]
Forgot to specify we use it in a CI, so we can't use `docker0` interface as the used IPs are the bridges ones on the different networkds created by each runner ;)

**Comment by lyrixx** [comment]
What is the the network interface so?
What do you get when you run `ip address   | grep docker`?
Can't you automate this?

**Comment by kissifrot** [comment]
They are named `br-<id>`, such as `br-0a35f3e2fdca`
I guess playing with custom-defined networks looks like the only way to achieve it with a CI

**Comment by lyrixx** [comment]
That weird. The router uses the "host" network_type. So there is no bridge (br). Are you sure `docker0` does not exist?

**Comment by kissifrot** [comment]
It does, but each runner instance (Gitlab CI) uses a different network

**Comment by kissifrot** [comment]
But I will redo a check in a few days to give you the exact context (as soon as I will have resolved chromium's crash with our website)

**Comment by lyrixx** [comment]
> It does, but each runner instance (Gitlab CI) uses a different network

yes, but this is not an issue. There is only one router and it's shared
