### ISSUE TITLE
Mapping ports on "run" command

### ISSUE THREAD

**Issue by matthieuwerner** [jolicode/docker-starter#31]
Hi there,

Is there any reason to avoid mapping ports on "run" command ?
https://github.com/jolicode/docker-starter/blob/c319756cc1ab1de8e4a3f29bea306695752f84c2/fabfile.py#L179

I just needed to add --service-ports option to the fabfile.py to run my container with port mapping embed.

:kissing_heart:

**Comment by lyrixx** [comment]
since we use docker-compose, it's better to set the port mapping in it.
But if you need something special, you can use port mapping via the run command.

Feel free to modify your fabfile. This docker-starter is not a lib, just a starter that must be customized according to your need.

**Comment by matthieuwerner** [comment]
--service-ports does actually the mapping defined in docker-compose.yaml.

**Comment by matthieuwerner** [comment]
CF PR : https://github.com/jolicode/docker-starter/pull/32

**Comment by lyrixx** [comment]
Thanks, I merged your PR
