### ISSUE TITLE
Consider switching to Debian as base image

### ISSUE THREAD

**Issue by pyrech** [jolicode/docker-starter#50]
Currently, we are using [Alpine](https://wiki.alpinelinux.org/wiki/Docker) as the base image for almost all services. At the time, this was the recommended base image and [Docker themself move their own images on Alpine](https://brianchristner.io/docker-is-moving-to-alpine-linux/) too.

2020 could be the year we switch back to Debian as nowadays they provide official image that no so big (like `debian:buster-slim`?). Here is some pro/cons:

Pros:
- a dev env more similar to classical prod env
- easier to use latest PHP version (almost impossible with Alpine)
- Alpine uses the `musl` library instead of classical libc, which used to break some tool like Blackfire

Cons:
- base image a bit bigger (~5Mo VS 60Mo)
- more different base images among all services thus more images to build and store
- bigger and different base images also slow CI build and can cost more credits (but should be less problematic than when we used normal Debian images weighting 500Mo)

Some read:
- https://phusion.github.io/baseimage-docker/
- https://github.com/docker-slim/docker-slim

**Comment by lyrixx** [comment]
I have no string opinion on this.
Should we consider using ubuntu ?

**Comment by lyrixx** [comment]
Note: docker-slim is 27Mb to download, then 69Mb on disk

**Comment by mykiwi** [comment]
Maybe I'm off-topic, but why don't you choose to use the official PHP image? It's available on Alpine and Debian.

**Comment by pyrech** [comment]
Not so off-topic :wink: We had this discussion internally many time since we use docker. I will try to summarize it here (hopefully without misunderstanding from me):

When we started using Alpine, our primary goal was to reduce the installation size and time. At the time, using Alpine base image and installing php package was tens or hundreds times faster than using the php official image, which:
- need to build PHP
- need to manually build PHP extensions and using stuff like phpsize to build with compatible parameters

Thus, these steps are way more complicated and slower than using packages from distributions.

We didn't give a try recently but I guess the situation didn't change that much. One way to tackle this complexity and duration could be to use a Docker registry, but again, that would complicate everything a lot when we compare that to just installing already built packages.

I hope my summary is correct and answer your question :slightly_smiling_face:

**Comment by lyrixx** [comment]
To complete the great comment of @pyrech 

It looks like the compilation of PHP is now done by default directly in the container.
**BUT** installing custom extension is not as easy as on regular alpine / debian:
```
>/home/gregoire docker run -it --rm php:7.4-alpine sh
/ # docker-php-ext-install amqp
error: /usr/src/php/ext/amqp does not exist

usage: /usr/local/bin/docker-php-ext-install [-jN] ext-name [ext-name ...]
   ie: /usr/local/bin/docker-php-ext-install gd mysqli
       /usr/local/bin/docker-php-ext-install pdo pdo_mysql
       /usr/local/bin/docker-php-ext-install -j5 gd mbstring mysqli pdo pdo_mysql shmop

if custom ./configure arguments are necessary, see docker-php-ext-configure

Possible values for ext-name:
bcmath bz2 calendar ctype curl dba dom enchant exif ffi fileinfo filter ftp gd gettext gmp hash iconv imap intl json ldap mbstring mysqli oci8 odbc opcache pcntl pdo pdo_dblib pdo_firebird pdo_mysql pdo_oci pdo_odbc pdo_pgsql pdo_sqlite pgsql phar posix pspell readline reflection session shmop simplexml snmp soap sockets sodium spl standard sysvmsg sysvsem sysvshm tidy tokenizer xml xmlreader xmlrpc xmlwriter xsl zend_test zip

Some of the above modules are already compiled into PHP; please check
the output of "php -i" to see which modules are already loaded.
/ # 
```

**Comment by lyrixx** [comment]
So, what we should do ?
We are going a new major release with a big BC break: [python 3 + invoke instead of fabric](https://github.com/jolicode/docker-starter/pull/61) so we have a window to break everything

* :tada: for sticking on bare alpine
* :rocket: to switch to debian

**Comment by bastnic** [comment]
Ce qui me chagrine le plus sur alpine c'est que les paquets php sont toujours sous php 7.3.

Pour le moment sur Sézane on est passé sur https://github.com/thecodingmachine/docker-images-php + image nginx à côté. C'est plutôt très (très) lourd, mais c'est maintenu, à jour et toutes les extensions que je veux sont gérées et fonctionnent au poil. J'ai donc quasi plus aucun Dockerfile et je m'en porte pas plus mal.

**Comment by bastnic** [comment]
What's trouble me the most it that alpine is still blocked on php 7.3 despite 74 is out since a few months. (see https://gitlab.alpinelinux.org/alpine/aports/merge_requests/2421).

On a big project of mine, I ditched all my heavy Dockerfile that resulted on tiny images for https://github.com/thecodingmachine/docker-images-php along with default nginx images (thecodingmachine project only support apache for now). It's waaaaay heavier but 1/ it maintained (by @moufmouf, whose I trust) 2/ have all the extensions I need 3/ is easily configurable 4/ deal with the default uid trouble. I don't have dockerfile anymore.

I would have loved to be less heavy but I only use this stack on dev + CI, I don't use the slim version so I avoid compilation.

**Comment by bastnic** [comment]
And on using default php:alpine image, I never succeded to set my extensions without dealing with bing headeach and with no success at all.

**Comment by lyrixx** [comment]
I made some bench (and the migration) : 
https://github.com/jolicode/docker-starter/pull/67
