### ISSUE TITLE
Improve the "help" / default, list the URL's on demand

### ISSUE THREAD

**Issue by damienalexandre** [jolicode/docker-starter#81]
At the end of "inv start" we print all the configured URL:

https://github.com/jolicode/docker-starter/blob/c7bdf3519845b4baa27f2a241acacf1c3ab7984d/tasks.py#L51-L53

![image](https://user-images.githubusercontent.com/225704/81306373-ae6f5680-907f-11ea-8018-cf5405e38e28.png)

That's awesome but we can never this is again, unless running "inv start" again.

Would be awesome if the help / task list could add this. Or add a "inv help" or "inv url" command to get the list back any time.

WDYT?

**Comment by lyrixx** [comment]
that's a very good suggestion :+1:

Would you mind to submit a PR?

**Comment by damienalexandre** [comment]
With the latest version the URL list does not get you all the exposed services.

You only get the URL going to the "frontend" app + any `extra_domains` URL (going to frontend only).

So we don't have the Treafik dashboard URL for example: http://127.0.0.1:8080/

If we add a service like maildev, we don't get the URL neither. 

This is related to this issue but that's also a regression I think.
