### ISSUE TITLE
Composer cache location

### ISSUE THREAD

**Issue by odolbeau** [jolicode/docker-starter#83]
The `composer global config cache-dir -q` command ran on the host can return a different result.

For example, on Debian 5.5 with composer 1.10.6 it's `~/.cache/composer` instead of `~/.composer/cache`.

As the volume mounted for the builder use the second option, a non reusable `~/.composer/cache` folder is created (with root) on my host.

I "solved" the problem using a symlink but if you have a more elegant solution, don't hesitate to tell me. :)

**Comment by lyrixx** [comment]
We can use the command you wrote to expose the "right" cache dir. Would you mind to submit a pr?

**Comment by odolbeau** [comment]
I'll take a look. ;)
