### ISSUE TITLE
Warning on /services/builder/Dockerfile with apt-key

### ISSUE THREAD

**Issue by matthieuwerner** [jolicode/docker-starter#97]
It should be great to remove the warning on the builder Dockerfile because of the programmatically usage of apt-key :
`Warning: apt-key output should not be parsed (stdout is not a terminal)`

It seems that there 2 ways to remove this warning :
- Using the environnement variable APT_KEY_DONT_WARN_ON_DANGEROUS_USAGE
- Redirect stdout to /dev/null

Both seems ignoring the real security content of the message 👎 

```
 apt-key is used to manage the list of keys used by apt to authenticate
   packages. Packages which have been authenticated using these keys will
   be considered trusted.
   Note that if usage of apt-key is desired the additional installation of
   the GNU Privacy Guard suite (packaged in gnupg) is required. For this
   reason alone the programmatic usage (especially in package maintainer
   scripts!) is strongly discouraged. Further more the output format of all
   commands is undefined and can and does change whenever the underlying
   commands change.  apt-key will try to detect such usage and generates
   warnings on stderr in these cases.
```
 => **For this reason alone the programmatic usage (especially in package maintainer scripts!) is strongly discouraged.**

Solution 1 : using an older version of nodejs who is officially supported by this version of Debian 😢 
Solution 2 : accept this warning (it's working with)
Solution 3 : ... feel free to propose any better solution :)

**Comment by lyrixx** [comment]
We don't use the output of `apt-key` so this is fine to me
https://github.com/jolicode/docker-starter/blob/master/infrastructure/docker/services/builder/Dockerfile#L7

So I'm for solution 2

**Comment by welcoMattic** [comment]
I'm ok with this warning too. We know what we do here, and it will disappear when Debian will provide a recent version of NodeJS, no ?

**Comment by pyrech** [comment]
Same here, let's just ignore it
