### ISSUE TITLE
[RFC] Plugin system

### ISSUE THREAD

**Issue by matthieuwerner** [jolicode/docker-starter#98]
Hello,

I think that it could be cool to add a plugin system, for specific use cases, that we don't want to implement directly in the starter.

Docker starter is a amazing tool to start a lot of types of projects using docker. We could perform some plugins to increase it relevance by adding a layer on it, with more dedicated containers and pre built configuration like :
- complex web applications (with functional build of elastic search, redis, varnish, etc. )
- serveless applications
- frontend applications
- ...

An idea of how it could be work : 
- https://alysivji.github.io/simple-plugin-system.html

**Comment by lyrixx** [comment]
Hello, 

Thanks for raising this up. But we already discuss that (internally). To summary, we prefer to keep something simple, with the minimum code to avoid shipping to much code in a simple application. And also to avoid end user to remove lot of code. Instead we prefer to add many cookbooks in the main README (which will be deleted in end user app).

I think I still have the same opinion on this topic.

ATM, you can have multi-application with worker, cron, redis, rabbitmq, es, postgres, mercure, etc very quickly (<10 minutes) by copying the main the README. It's almost a no-brainer task so it should be easy for everyone.

But I'm not close for new features, but on this one I prefer the documentation over a plugin system.

Let's wait to know what other people think about it before taking an decision

**Comment by pyrech** [comment]
I agree with @lyrixx. Too much work to maintain a plugin system IMO. :-1: from me

**Comment by welcoMattic** [comment]
I'm not in favor of a plugin system. Cookbooks are a very nice option. All of common docker/php project have a same base (frontend, database). All others services depends of the project itself. As @lyrixx says, it's quite simple and fast to add Elasticsearch, Mercure, even switch from pgsql to mariadb. I think that adding a plugin system will make harder and more complex the maintenance of this project. So, :-1: for me too
